### ISSUE TITLE
Make separate unit?

### ISSUE THREAD

**Issue by Alexey-T** [Raf20076/Lazspell#1]
As i see, Lazspell code is in the same unit as demo, mainunit. but for other apps, we need separate unit with Lazspell api, and demo must use this unit.

**Comment by Raf20076** [comment]
Actually Lazspell is a demo program, not component. Lazspell usues hunspell wrapper (hunspell.pas), the mainunit.pas is a program code. The code is well commented, so it could be used or converted for your program. If you want to make an component of it feel free to do it.  For example functions like ArrayValueCount, StripOffNonCharacter, ReplaceCarriageReturn, FindInMemo could be in a separate unit like function.pas, event ButtonCheckSpellingClick in seperate unit like checkspell.pas etc
This is just an example. If you want to improve it you are welcome.
